const TIMEZONE_PARAMS = [
  { origin: 'mumbai', destination: 'dubai' },
  { origin: 'singapore', destination: 'san-francisco' },
  { origin: 'london', destination: 'tokyo' },
  { origin: 'los-angeles', destination: 'sydney' },
  { origin: 'paris', destination: 'new-york' },
  { origin: 'beijing', destination: 'singapore' },
  { origin: 'johannesburg', destination: 'dubai' },
  { origin: 'sao-paulo', destination: 'london' },
  { origin: 'new-york', destination: 'london' },
  { origin: 'mumbai', destination: 'london' },
  { origin: 'tokyo', destination: 'new-york' },
  { origin: 'singapore', destination: 'london' },
  { origin: 'san-francisco', destination: 'tokyo' },
  { origin: 'berlin', destination: 'new-york' },
  { origin: 'paris', destination: 'dubai' },
  { origin: 'london', destination: 'sydney' },
  { origin: 'dubai', destination: 'singapore' },
  { origin: 'new-york', destination: 'mumbai' },
  { origin: 'chicago', destination: 'tokyo' },
  { origin: 'hong-kong', destination: 'london' },
  { origin: 'toronto', destination: 'berlin' },
  { origin: 'dubai', destination: 'london' },
  { origin: 'mumbai', destination: 'new-york' },
  { origin: 'san-francisco', destination: 'singapore' },
  { origin: 'sydney', destination: 'london' },
  { origin: 'tokyo', destination: 'paris' },
  { origin: 'berlin', destination: 'singapore' },
  { origin: 'beijing', destination: 'new-york' },
  { origin: 'toronto', destination: 'london' },
  { origin: 'dubai', destination: 'sydney' },
  { origin: 'berlin', destination: 'sao-paulo' },
  { origin: 'london', destination: 'delhi' },
  { origin: 'san-francisco', destination: 'tel-aviv-yafo' },
  { origin: 'frankfurt', destination: 'singapore' },
  { origin: 'seoul', destination: 'sydney' },
  { origin: 'zurich', destination: 'hong-kong' },
  { origin: 'mexico-city', destination: 'tokyo' },
  { origin: 'berlin', destination: 'cape-town' },
  { origin: 'stockholm', destination: 'bengaluru' },
  { origin: 'zurich', destination: 'new-york' },
  { origin: 'seoul', destination: 'san-francisco' },
  { origin: 'cairo', destination: 'istanbul' },
  { origin: 'mexico-city', destination: 'seoul' },
  { origin: 'seoul', destination: 'london' },
  { origin: 'mumbai', destination: 'toronto' },
  { origin: 'auckland', destination: 'los-angeles' },
  { origin: 'istanbul', destination: 'new-york' },
  { origin: 'dubai', destination: 'shanghai' },
  { origin: 'sydney', destination: 'santiago' },
  { origin: 'delhi', destination: 'beijing' },
  { origin: 'toronto', destination: 'melbourne' },
  { origin: 'istanbul', destination: 'bangkok' },
  { origin: 'seattle', destination: 'taipei' },
  { origin: 'chicago', destination: 'lisbon' },
  { origin: 'buenos-aires', destination: 'madrid' },
  { origin: 'lagos', destination: 'london' },
  { origin: 'nairobi', destination: 'amsterdam' },
  { origin: 'mumbai', destination: 'tokyo' },
  { origin: 'manila', destination: 'dubai' },
  { origin: 'bangkok', destination: 'new-york' },
  { origin: 'new-york', destination: 'tokyo' },
  { origin: 'jakarta', destination: 'london' },
  { origin: 'manila', destination: 'new-york' },
  { origin: 'los-angeles', destination: 'london' },
  { origin: 'lagos', destination: 'new-york' },
  { origin: 'nairobi', destination: 'london' },
  { origin: 'seoul', destination: 'vancouver' },
  { origin: 'los-angeles', destination: 'mumbai' },
];

const JETLAG_PARAMS = [
  { origin: 'mumbai', destination: 'london' },
  { origin: 'sydney', destination: 'los-angeles' },
  { origin: 'new-york', destination: 'london' },
  { origin: 'tokyo', destination: 'paris' },
  { origin: 'los-angeles', destination: 'sydney' },
  { origin: 'san-francisco', destination: 'tokyo' },
  { origin: 'london', destination: 'dubai' },
  { origin: 'berlin', destination: 'bangkok' },
  { origin: 'san-francisco', destination: 'paris' },
  { origin: 'paris', destination: 'new-york' },
  { origin: 'dubai', destination: 'singapore' },
  { origin: 'toronto', destination: 'tokyo' },
  { origin: 'sao-paulo', destination: 'frankfurt' },
  { origin: 'chicago', destination: 'rome' },
  { origin: 'london', destination: 'singapore' },
  { origin: 'dubai', destination: 'sydney' },
  { origin: 'new-york', destination: 'tokyo' },
  { origin: 'san-francisco', destination: 'sydney' },
  { origin: 'paris', destination: 'tokyo' },
  { origin: 'shanghai', destination: 'san-francisco' },
  { origin: 'singapore', destination: 'london' },
  { origin: 'dubai', destination: 'new-york' },
  { origin: 'bengaluru', destination: 'san-francisco' },
  { origin: 'london', destination: 'tokyo' },
  { origin: 'new-york', destination: 'sydney' },
  { origin: 'cairo', destination: 'beijing' },
  { origin: 'reykjavik', destination: 'tokyo' },
  { origin: 'honolulu', destination: 'dubai' },
  { origin: 'anchorage', destination: 'singapore' },
  { origin: 'mexico-city', destination: 'seoul' },
  { origin: 'new-york', destination: 'shanghai' },
];

const DST_PARAMS = [
  { city: 'london' },
  { city: 'new-york' },
  { city: 'sydney' },
  { city: 'sao-paulo' },
  { city: 'berlin' },
  { city: 'chicago' },
  { city: 'los-angeles' },
  { city: 'paris' },
  { city: 'toronto' },
  { city: 'mexico-city' },
  { city: 'tokyo' },
  { city: 'dubai' },
  { city: 'singapore' },
  { city: 'mumbai' },
  { city: 'cairo' },
  { city: 'moscow' },
  { city: 'atlanta' },
  { city: 'istanbul' },
  { city: 'hong-kong' },
  { city: 'shanghai' },
  { city: 'johannesburg' },
  { city: 'bangkok' },
  { city: 'delhi' },
  { city: 'seoul' },
  { city: 'buenos-aires' },
  { city: 'miami' },
  { city: 'madrid' },
  { city: 'lagos' },
  { city: 'rio-de-janeiro' },
  { city: 'cape-town' },
];

const PATHS = {
  timezoneConverter: 'timezone-converter',
  dstChecker: 'dst-checker',
  jetLagPlanner: 'jet-lag-planner',
  downloadTimezoneList: 'download-timezone-list',

  jetLagFromMumbaiToLondon: 'jet-lag/from/mumbai/to/london',
  jetLagFromSydneyToLosAngeles: 'jet-lag/from/sydney/to/los-angeles',
  jetLagFromNewYorkToLondon: 'jet-lag/from/new-york/to/london',
  jetLagFromTokyoToParis: 'jet-lag/from/tokyo/to/paris',
  jetLagFromLosAngelesToSydney: 'jet-lag/from/los-angeles/to/sydney',
  jetLagFromSanFranciscoToTokyo: 'jet-lag/from/san-francisco/to/tokyo',
  jetLagFromLondonToDubai: 'jet-lag/from/london/to/dubai',
  jetLagFromBerlinToBangkok: 'jet-lag/from/berlin/to/bangkok',
  jetLagFromSanFranciscoToParis: 'jet-lag/from/san-francisco/to/paris',
  jetLagFromParisToNewYork: 'jet-lag/from/paris/to/new-york',
  jetLagFromDubaiToSingapore: 'jet-lag/from/dubai/to/singapore',
  jetLagFromTorontoToTokyo: 'jet-lag/from/toronto/to/tokyo',
  jetLagFromSaoPauloToFrankfurt: 'jet-lag/from/sao-paulo/to/frankfurt',
  jetLagFromChicagoToRome: 'jet-lag/from/chicago/to/rome',
  jetLagFromLondonToSingapore: 'jet-lag/from/london/to/singapore',
  jetLagFromDubaiToSydney: 'jet-lag/from/dubai/to/sydney',
  jetLagFromNewYorkToTokyo: 'jet-lag/from/new-york/to/tokyo',
  jetLagFromSanFranciscoToSydney: 'jet-lag/from/san-francisco/to/sydney',
  jetLagFromParisToTokyo: 'jet-lag/from/paris/to/tokyo',
  jetLagFromShanghaiToSanFrancisco: 'jet-lag/from/shanghai/to/san-francisco',
  jetLagFromSingaporeToLondon: 'jet-lag/from/singapore/to/london',
  jetLagFromDubaiToNewYork: 'jet-lag/from/dubai/to/new-york',
  jetLagFromBengaluruToSanFrancisco: 'jet-lag/from/bengaluru/to/san-francisco',
  jetLagFromLondonToTokyo: 'jet-lag/from/london/to/tokyo',
  jetLagFromNewYorkToSydney: 'jet-lag/from/new-york/to/sydney',
  jetLagFromCairoToBeijing: 'jet-lag/from/cairo/to/beijing',
  jetLagFromReykjavikToTokyo: 'jet-lag/from/reykjavik/to/tokyo',
  jetLagFromHonoluluToDubai: 'jet-lag/from/honolulu/to/dubai',
  jetLagFromAnchorageToSingapore: 'jet-lag/from/anchorage/to/singapore',
  jetLagFromMexicoCityToSeoul: 'jet-lag/from/mexico-city/to/seoul',

  dstInLondon: 'dst-in/london',
  dstInNewYork: 'dst-in/new-york',
  dstInSydney: 'dst-in/sydney',
  dstInSaoPaulo: 'dst-in/sao-paulo',
  dstInBerlin: 'dst-in/berlin',
  dstInChicago: 'dst-in/chicago',
  dstInLosAngeles: 'dst-in/los-angeles',
  dstInParis: 'dst-in/paris',
  dstInToronto: 'dst-in/toronto',
  dstInMexicoCity: 'dst-in/mexico-city',
  dstInTokyo: 'dst-in/tokyo',
  dstInDubai: 'dst-in/dubai',
  dstInSingapore: 'dst-in/singapore',
  dstInMumbai: 'dst-in/mumbai',
  dstInCairo: 'dst-in/cairo',
  dstInMoscow: 'dst-in/moscow',
  dstInAtlanta: 'dst-in/atlanta',
  dstInIstanbul: 'dst-in/istanbul',
  dstInHongKong: 'dst-in/hong-kong',
  dstInShanghai: 'dst-in/shanghai',
  dstInJohannesburg: 'dst-in/johannesburg',
  dstInBangkok: 'dst-in/bangkok',
  dstInDelhi: 'dst-in/delhi',
  dstInSeoul: 'dst-in/seoul',
  dstInBuenosAires: 'dst-in/buenos-aires',
  dstInMiami: 'dst-in/miami',
  dstInMadrid: 'dst-in/madrid',
  dstInLagos: 'dst-in/lagos',
  dstInRioDeJaneiro: 'dst-in/rio-de-janeiro',
  dstInCapeTown: 'dst-in/cape-town',

  timezoneFromMumbaiToDubai: 'timezone/from/mumbai/to/dubai',
  timezoneFromSingaporeToSanFrancisco:
    'timezone/from/singapore/to/san-francisco',
  timezoneFromLondonToTokyo: 'timezone/from/london/to/tokyo',
  timezoneFromLosAngelesToSydney: 'timezone/from/los-angeles/to/sydney',
  timezoneFromParisToNewYork: 'timezone/from/paris/to/new-york',
  timezoneFromBeijingToSingapore: 'timezone/from/beijing/to/singapore',
  timezoneFromJohannesburgToDubai: 'timezone/from/johannesburg/to/dubai',
  timezoneFromSaoPauloToLondon: 'timezone/from/sao-paulo/to/london',
  timezoneFromNewYorkToLondon: 'timezone/from/new-york/to/london',
  timezoneFromMumbaiToLondon: 'timezone/from/mumbai/to/london',
  timezoneFromTokyoToNewYork: 'timezone/from/tokyo/to/new-york',
  timezoneFromSingaporeToLondon: 'timezone/from/singapore/to/london',
  timezoneFromSanFranciscoToTokyo: 'timezone/from/san-francisco/to/tokyo',
  timezoneFromBerlinToNewYork: 'timezone/from/berlin/to/new-york',
  timezoneFromParisToDubai: 'timezone/from/paris/to/dubai',
  timezoneFromLondonToSydney: 'timezone/from/london/to/sydney',
  timezoneFromDubaiToSingapore: 'timezone/from/dubai/to/singapore',
  timezoneFromNewYorkToMumbai: 'timezone/from/new-york/to/mumbai',
  timezoneFromChicagoToTokyo: 'timezone/from/chicago/to/tokyo',
  timezoneFromHongKongToLondon: 'timezone/from/hong-kong/to/london',
  timezoneFromTorontoToBerlin: 'timezone/from/toronto/to/berlin',
  timezoneFromDubaiToLondon: 'timezone/from/dubai/to/london',
  timezoneFromMumbaiToNewYork: 'timezone/from/mumbai/to/new-york',
  timezoneFromSanFranciscoToSingapore:
    'timezone/from/san-francisco/to/singapore',
  timezoneFromSydneyToLondon: 'timezone/from/sydney/to/london',
  timezoneFromTokyoToParis: 'timezone/from/tokyo/to/paris',
  timezoneFromBerlinToSingapore: 'timezone/from/berlin/to/singapore',
  timezoneFromBeijingToNewYork: 'timezone/from/beijing/to/new-york',
  timezoneFromTorontoToLondon: 'timezone/from/toronto/to/london',
  timezoneFromDubaiToSydney: 'timezone/from/dubai/to/sydney',
  timezoneFromBerlinToSaoPaulo: 'timezone/from/berlin/to/sao-paulo',
  timezoneFromNewYorkToShanghai: 'timezone/from/new-york/to/shanghai',
  timezoneFromLondonToDelhi: 'timezone/from/london/to/delhi',
  timezoneFromSanFranciscoToTelAvivYafo:
    'timezone/from/san-francisco/to/tel-aviv-yafo',
  timezoneFromFrankfurtToSingapore: 'timezone/from/frankfurt/to/singapore',
  timezoneFromSeoulToSydney: 'timezone/from/seoul/to/sydney',
  timezoneFromZurichToHongKong: 'timezone/from/zurich/to/hong-kong',
  timezoneFromMexicoCityToTokyo: 'timezone/from/mexico-city/to/tokyo',
  timezoneFromBerlinToCapeTown: 'timezone/from/berlin/to/cape-town',
  timezoneFromStockholmToBengaluru: 'timezone/from/stockholm/to/bengaluru',
  timezoneFromZurichToNewYork: 'timezone/from/zurich/to/new-york',
  timezoneFromSeoulToSanFrancisco: 'timezone/from/seoul/to/san-francisco',
  timezoneFromCairoToIstanbul: 'timezone/from/cairo/to/istanbul',
  timezoneFromMexicoCityToSeoul: 'timezone/from/mexico-city/to/seoul',
  timezoneFromSeoulToLondon: 'timezone/from/seoul/to/london',
  timezoneFromMumbaiToToronto: 'timezone/from/mumbai/to/toronto',
  timezoneFromAucklandToLosAngeles: 'timezone/from/auckland/to/los-angeles',
  timezoneFromIstanbulToNewYork: 'timezone/from/istanbul/to/new-york',
  timezoneFromDubaiToShanghai: 'timezone/from/dubai/to/shanghai',
  timezoneFromSydneyToSantiago: 'timezone/from/sydney/to/santiago',
  timezoneFromDelhiToBeijing: 'timezone/from/delhi/to/beijing',
  timezoneFromTorontoToMelbourne: 'timezone/from/toronto/to/melbourne',
  timezoneFromIstanbulToBangkok: 'timezone/from/istanbul/to/bangkok',
  timezoneFromSeattleToTaipei: 'timezone/from/seattle/to/taipei',
  timezoneFromChicagoToLisbon: 'timezone/from/chicago/to/lisbon',
  timezoneFromBuenosAiresToMadrid: 'timezone/from/buenos-aires/to/madrid',
  timezoneFromLagosToLondon: 'timezone/from/lagos/to/london',
  timezoneFromNairobiToAmsterdam: 'timezone/from/nairobi/to/amsterdam',
  timezoneFromMumbaiToTokyo: 'timezone/from/mumbai/to/tokyo',
  timezoneFromManilaToDubai: 'timezone/from/manila/to/dubai',
  timezoneFromBangkokToNewYork: 'timezone/from/bangkok/to/new-york',
  timezoneFromNewYorkToTokyo: 'timezone/from/new-york/to/tokyo',
  timezoneFromJakartaToLondon: 'timezone/from/jakarta/to/london',
  timezoneFromManilaToNewYork: 'timezone/from/manila/to/new-york',
  timezoneFromLosAngelesToLondon: 'timezone/from/los-angeles/to/london',
  timezoneFromLagosToNewYork: 'timezone/from/lagos/to/new-york',
  timezoneFromNairobiToLondon: 'timezone/from/nairobi/to/london',
  timezoneFromSeoulToVancouver: 'timezone/from/seoul/to/vancouver',
  timezoneFromDohaToSingapore: 'timezone/from/doha/to/singapore',
  timezoneFromLosAngelesToMumbai: 'timezone/from/los-angeles/to/mumbai',
};

const PATHS_REVERSE = Object.fromEntries(
  Object.entries(PATHS).map(([k, v]) => [v, k]),
);

const DATES = {
  [PATHS.timezoneConverter]: '2025-10-01T00:00:00Z',
  [PATHS.dstChecker]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagPlanner]: '2025-10-01T00:00:00Z',
  [PATHS.downloadTimezoneList]: '2025-10-01T00:00:00Z',

  [PATHS.jetLagFromMumbaiToLondon]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSydneyToLosAngeles]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromNewYorkToLondon]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromTokyoToParis]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromLosAngelesToSydney]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSanFranciscoToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromLondonToDubai]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromBerlinToBangkok]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSanFranciscoToParis]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromParisToNewYork]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromDubaiToSingapore]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromTorontoToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSaoPauloToFrankfurt]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromChicagoToRome]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromLondonToSingapore]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromDubaiToSydney]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromNewYorkToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSanFranciscoToSydney]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromParisToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromShanghaiToSanFrancisco]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromSingaporeToLondon]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromDubaiToNewYork]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromBengaluruToSanFrancisco]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromLondonToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromNewYorkToSydney]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromCairoToBeijing]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromReykjavikToTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromHonoluluToDubai]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromAnchorageToSingapore]: '2025-10-01T00:00:00Z',
  [PATHS.jetLagFromMexicoCityToSeoul]: '2025-10-01T00:00:00Z',

  [PATHS.dstInLondon]: '2025-10-01T00:00:00Z',
  [PATHS.dstInNewYork]: '2025-10-01T00:00:00Z',
  [PATHS.dstInSydney]: '2025-10-01T00:00:00Z',
  [PATHS.dstInSaoPaulo]: '2025-10-01T00:00:00Z',
  [PATHS.dstInBerlin]: '2025-10-01T00:00:00Z',
  [PATHS.dstInChicago]: '2025-10-01T00:00:00Z',
  [PATHS.dstInLosAngeles]: '2025-10-01T00:00:00Z',
  [PATHS.dstInParis]: '2025-10-01T00:00:00Z',
  [PATHS.dstInToronto]: '2025-10-01T00:00:00Z',
  [PATHS.dstInMexicoCity]: '2025-10-01T00:00:00Z',
  [PATHS.dstInTokyo]: '2025-10-01T00:00:00Z',
  [PATHS.dstInDubai]: '2025-10-01T00:00:00Z',
  [PATHS.dstInSingapore]: '2025-10-01T00:00:00Z',
  [PATHS.dstInMumbai]: '2025-10-01T00:00:00Z',
  [PATHS.dstInCairo]: '2025-10-01T00:00:00Z',
  [PATHS.dstInMoscow]: '2025-10-01T00:00:00Z',
  [PATHS.dstInAtlanta]: '2025-10-01T00:00:00Z',
  [PATHS.dstInIstanbul]: '2025-10-01T00:00:00Z',
  [PATHS.dstInHongKong]: '2025-10-01T00:00:00Z',
  [PATHS.dstInShanghai]: '2025-10-01T00:00:00Z',
  [PATHS.dstInJohannesburg]: '2025-10-01T00:00:00Z',
  [PATHS.dstInBangkok]: '2025-10-01T00:00:00Z',
  [PATHS.dstInDelhi]: '2025-10-01T00:00:00Z',
  [PATHS.dstInSeoul]: '2025-10-01T00:00:00Z',
  [PATHS.dstInBuenosAires]: '2025-10-01T00:00:00Z',
  [PATHS.dstInMiami]: '2025-10-01T00:00:00Z',
  [PATHS.dstInMadrid]: '2025-10-01T00:00:00Z',
  [PATHS.dstInLagos]: '2025-10-01T00:00:00Z',
  [PATHS.dstInRioDeJaneiro]: '2025-10-01T00:00:00Z',
  [PATHS.dstInCapeTown]: '2025-10-01T00:00:00Z',

  [PATHS.timezoneFromBerlinToSaoPaulo]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromNewYorkToShanghai]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromLondonToDelhi]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSanFranciscoToTelAvivYafo]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromFrankfurtToSingapore]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSeoulToSydney]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromZurichToHongKong]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromMexicoCityToTokyo]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromBerlinToCapeTown]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromStockholmToBengaluru]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromZurichToNewYork]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSeoulToSanFrancisco]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromCairoToIstanbul]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromMexicoCityToSeoul]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSeoulToLondon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromMumbaiToToronto]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromAucklandToLosAngeles]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromIstanbulToNewYork]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromDubaiToShanghai]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSydneyToSantiago]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromDelhiToBeijing]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromTorontoToMelbourne]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromIstanbulToBangkok]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSeattleToTaipei]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromChicagoToLisbon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromBuenosAiresToMadrid]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromLagosToLondon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromNairobiToAmsterdam]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromMumbaiToTokyo]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromManilaToDubai]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromBangkokToNewYork]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromNewYorkToTokyo]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromJakartaToLondon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromManilaToNewYork]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromLosAngelesToLondon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromLagosToNewYork]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromNairobiToLondon]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromSeoulToVancouver]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromDohaToSingapore]: '2025-11-24T00:00:00Z',
  [PATHS.timezoneFromLosAngelesToMumbai]: '2025-11-24T00:00:00Z',
};

export {
  TIMEZONE_PARAMS,
  JETLAG_PARAMS,
  DST_PARAMS,
  PATHS,
  PATHS_REVERSE,
  DATES,
};
